# Generated by Django 6.0.6 on 2026-08-17 06:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, help_text='Organizer or admin who scanned the QR code.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_rsvps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text="Unique token encoded in the attendee's QR code.", unique=True),
        ),
    ]
